# Example Configuration: Monastier Online Project

project:
  name: "Monastier Online"
  slug: "monastier-online"
  description: "Webový portál pre pravoslávnych veriacich na Slovensku a v Maďarsku"

github:
  username: "rauschiccsk"
  repo_name: "orthodox-portal"
  visibility: "private"

developer:
  name: "ICC"
  email: "rausch@icc.sk"

paths:
  local_dev: "c:\\Development\\orthodox-portal"
  local_deploy: "c:\\Deployment\\orthodox-portal"

tech_stack:
  backend:
    - "fastapi"
    - "sqlalchemy"
  frontend:
    - "jinja2"
    - "tailwindcss"
    - "alpine.js"
  databases:
    - "postgresql"
    - "mongodb"
    - "redis"
  automation:
    - "n8n"
    - "celery"
  other:
    - "minio"

optional:
  domain: "monastier.online"
  contact_email: "monastierkomarno@gmail.com"
  project_type: "web_application"

features:
  include_auth: true
  include_api_docs: true
  include_tests: true
  include_docker: false
  include_cicd: false
  include_migrations: true

deployment:
  server_os: "Ubuntu 22.04"
  python_version: "3.11"
  server_specs:
    cpu: "4 cores"
    ram: "8GB"
    disk: "100GB SSD"